<!DOCTYPE html>
<html>
<head>
    <!-- Latest compiled and minified CSS -->
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <style>
        th, td {
            padding: 0 1em 0 0;
        }
    </style>
</head>
<body>
<div class="container>">
<!--    <div class="row">-->
        <div class="col-md-12">
            <?php echo $body; ?>
        </div>
<!--    </div>-->
</div>
</body>
</html>